import type {
  AgendaEvent,
  Country,
  CountryCode,
  Document,
  Dossier,
  Folder,
  Forum,
  NewsItem,
  Topic,
  TopicMeta,
} from './types'

export const COUNTRIES: Country[] = [
  { code: 'AR', name: 'Argentina', flag: '🇦🇷' },
  { code: 'BR', name: 'Brasil', flag: '🇧🇷' },
  { code: 'UY', name: 'Uruguay', flag: '🇺🇾' },
  { code: 'PY', name: 'Paraguay', flag: '🇵🇾' },
  { code: 'CL', name: 'Chile', flag: '🇨🇱' },
  { code: 'BO', name: 'Bolivia', flag: '🇧🇴' },
  { code: 'PE', name: 'Perú', flag: '🇵🇪' },
  { code: 'CO', name: 'Colombia', flag: '🇨🇴' },
]

export const TOPICS: TopicMeta[] = [
  { id: 'ambiente', label: 'Ambiente', shortLabel: 'Ambiente' },
  { id: 'integracion-regional', label: 'Integración regional', shortLabel: 'Integración' },
  { id: 'corredores-bioceanicos', label: 'Corredores bioceánicos', shortLabel: 'Corredores' },
  { id: 'genero', label: 'Género', shortLabel: 'Género' },
  { id: 'educacion', label: 'Educación', shortLabel: 'Educación' },
  { id: 'salud', label: 'Salud', shortLabel: 'Salud' },
  { id: 'energia', label: 'Energía', shortLabel: 'Energía' },
  { id: 'rio-uruguay', label: 'Río Uruguay', shortLabel: 'Río Uruguay' },
  { id: 'mercosur', label: 'Integración MERCOSUR', shortLabel: 'MERCOSUR' },
  { id: 'rrii', label: 'Relaciones internacionales', shortLabel: 'RRII' },
  { id: 'seguridad', label: 'Seguridad', shortLabel: 'Seguridad' },
  { id: 'economia-regional', label: 'Economía regional', shortLabel: 'Economía' },
]

export const countryByCode = (code: CountryCode): Country =>
  COUNTRIES.find(c => c.code === code) ?? COUNTRIES[0]

export const topicById = (id: Topic): TopicMeta =>
  TOPICS.find(t => t.id === id) ?? TOPICS[0]

export const NEWS: NewsItem[] = [
  {
    id: 'n1',
    title: 'Nueva reglamentación ambiental en Brasil',
    country: 'BR',
    topic: 'ambiente',
    type: 'decreto',
    date: '2026-05-05',
    relevance: 'alta',
    excerpt: 'El decreto actualiza criterios de control ambiental, incorpora obligaciones de reporte y refuerza la coordinación con autoridades competentes.',
    source: 'Boletín Oficial — Brasil',
  },
  {
    id: 'n2',
    title: 'Proyecto sobre corredores logísticos en Argentina',
    country: 'AR',
    topic: 'corredores-bioceanicos',
    type: 'ley',
    date: '2026-05-04',
    relevance: 'alta',
    excerpt: 'Iniciativa que ordena financiamiento, infraestructura y coordinación interjurisdiccional para corredores bioceánicos del cono sur.',
    source: 'HCDN — Cámara de Diputados Argentina',
  },
  {
    id: 'n3',
    title: 'Informe regional sobre integración energética',
    country: 'UY',
    topic: 'energia',
    type: 'informe',
    date: '2026-05-03',
    relevance: 'media',
    excerpt: 'Análisis de oportunidades de cooperación entre operadores eléctricos de la región y propuestas para mecanismos comunes.',
    source: 'Comisión técnica regional',
  },
  {
    id: 'n4',
    title: 'Nuevo marco normativo sobre Río Uruguay',
    country: 'UY',
    topic: 'rio-uruguay',
    type: 'reglamento',
    date: '2026-05-02',
    relevance: 'alta',
    excerpt: 'Ajustes a criterios de monitoreo, reporte y coordinación binacional sobre la cuenca del Río Uruguay.',
    source: 'Comisión Administradora del Río Uruguay',
  },
  {
    id: 'n5',
    title: 'Avances en ley de paridad de género — Paraguay',
    country: 'PY',
    topic: 'genero',
    type: 'ley',
    date: '2026-05-01',
    relevance: 'media',
    excerpt: 'Proyecto que establece criterios de paridad para listas legislativas y representación en organismos públicos.',
    source: 'Senado de la República del Paraguay',
  },
  {
    id: 'n6',
    title: 'Comunicado UPM sobre cooperación legislativa digital',
    country: 'UY',
    topic: 'integracion-regional',
    type: 'comunicado',
    date: '2026-04-29',
    relevance: 'alta',
    excerpt: 'La UPM impulsa una nueva etapa de cooperación legislativa digital entre los parlamentos de la región.',
    source: 'Secretaría UPM',
  },
  {
    id: 'n7',
    title: 'Informe técnico — Educación pública regional',
    country: 'CL',
    topic: 'educacion',
    type: 'informe',
    date: '2026-04-28',
    relevance: 'media',
    excerpt: 'Comparativa de marcos normativos sobre financiamiento de educación pública entre países del cono sur.',
    source: 'Centro de estudios legislativos',
  },
  {
    id: 'n8',
    title: 'MERCOSUR — Acuerdo sobre cooperación aduanera',
    country: 'AR',
    topic: 'mercosur',
    type: 'acta',
    date: '2026-04-27',
    relevance: 'alta',
    excerpt: 'Acta de la última reunión de coordinación aduanera entre estados parte y observaciones operativas.',
    source: 'Secretaría MERCOSUR',
  },
  {
    id: 'n9',
    title: 'Ley marco de salud regional en Bolivia',
    country: 'BO',
    topic: 'salud',
    type: 'ley',
    date: '2026-04-25',
    relevance: 'media',
    excerpt: 'Establece principios para programas de salud pública con énfasis en zonas fronterizas y poblaciones vulnerables.',
    source: 'Asamblea Plurinacional — Bolivia',
  },
  {
    id: 'n10',
    title: 'Decreto sobre RRII — Perú',
    country: 'PE',
    topic: 'rrii',
    type: 'decreto',
    date: '2026-04-24',
    relevance: 'baja',
    excerpt: 'Reordena criterios de coordinación entre cancillería y comisiones legislativas para tratados regionales.',
    source: 'Diario Oficial — Perú',
  },
]

export const DOCUMENTS: Document[] = [
  {
    id: 'd1',
    title: 'Acta del Foro UPM de Medio Ambiente',
    type: 'acta',
    topic: 'ambiente',
    status: 'oficial',
    date: '2026-04-22',
    forum: 'Medio Ambiente',
    excerpt: 'Acuerdos del foro sobre coordinación normativa ambiental entre los parlamentos de la región.',
  },
  {
    id: 'd2',
    title: 'Informe regional sobre corredores bioceánicos',
    type: 'informe',
    topic: 'corredores-bioceanicos',
    status: 'curado',
    date: '2026-04-15',
    forum: 'Corredores Bioceánicos',
    excerpt: 'Diagnóstico técnico sobre infraestructura, financiamiento y coordinación regional para corredores.',
  },
  {
    id: 'd3',
    title: 'Convenio de cooperación legislativa regional',
    type: 'convenio',
    topic: 'integracion-regional',
    status: 'oficial',
    date: '2026-03-20',
    excerpt: 'Marco institucional de cooperación entre parlamentos para iniciativas conjuntas y reciprocidad técnica.',
  },
  {
    id: 'd4',
    title: 'Documento base sobre integración MERCOSUR',
    type: 'dossier',
    topic: 'mercosur',
    status: 'oficial',
    date: '2026-03-10',
    excerpt: 'Antecedentes, principios y prioridades estratégicas para la integración del MERCOSUR.',
  },
  {
    id: 'd5',
    title: 'Resumen normativo sobre protección ambiental',
    type: 'informe',
    topic: 'ambiente',
    status: 'curado',
    date: '2026-03-05',
    excerpt: 'Comparativa de marcos normativos ambientales entre países del cono sur.',
  },
  {
    id: 'd6',
    title: 'Minuta de reunión UPM — Río Uruguay',
    type: 'minuta',
    topic: 'rio-uruguay',
    status: 'oficial',
    date: '2026-02-28',
    forum: 'Río Uruguay',
    excerpt: 'Minuta de la reunión de coordinación bilateral sobre monitoreo y cooperación.',
  },
  {
    id: 'd7',
    title: 'Informe académico sobre legislación comparada',
    type: 'informe',
    topic: 'integracion-regional',
    status: 'aporte',
    date: '2026-02-12',
    forum: 'Académico',
    excerpt: 'Trabajo académico aportado al foro sobre técnicas legislativas comparadas.',
  },
  {
    id: 'd8',
    title: 'Ley de Protección Ambiental Regional',
    type: 'ley',
    topic: 'ambiente',
    status: 'oficial',
    country: 'UY',
    date: '2025-12-18',
    excerpt: 'Marco regional de protección ambiental con obligaciones de reporte, evaluación y coordinación.',
  },
  {
    id: 'd9',
    title: 'Acuerdo de cooperación aduanera MERCOSUR',
    type: 'convenio',
    topic: 'mercosur',
    status: 'oficial',
    date: '2025-11-30',
    excerpt: 'Acuerdo entre estados parte sobre criterios y procesos comunes para coordinación aduanera.',
  },
  {
    id: 'd10',
    title: 'Comunicado UPM — Cooperación legislativa digital',
    type: 'comunicado',
    topic: 'integracion-regional',
    status: 'oficial',
    date: '2026-04-29',
    excerpt: 'Comunicado oficial sobre la nueva etapa de cooperación legislativa digital regional.',
  },
  {
    id: 'd11',
    title: 'Convenio UPM sobre Río Uruguay',
    type: 'convenio',
    topic: 'rio-uruguay',
    status: 'oficial',
    date: '2026-01-22',
    forum: 'Río Uruguay',
    excerpt: 'Convenio sobre criterios institucionales para abordaje del Río Uruguay.',
  },
  {
    id: 'd12',
    title: 'Agenda preliminar — Foro Corredores Bioceánicos',
    type: 'minuta',
    topic: 'corredores-bioceanicos',
    status: 'curado',
    date: '2026-04-30',
    forum: 'Corredores Bioceánicos',
    excerpt: 'Agenda preliminar y temas prioritarios del próximo Foro de Corredores Bioceánicos.',
  },
]

export const DOSSIERS: Dossier[] = [
  {
    id: 'ds1',
    title: 'Dossier — Corredores bioceánicos',
    topic: 'corredores-bioceanicos',
    updatedAt: '2026-05-04',
    summary:
      'Oportunidades de integración física, logística y económica entre países de la región. Desafíos: coordinación normativa, financiamiento y articulación entre organismos.',
    sections: [
      { title: 'Resumen ejecutivo', body: 'El tema combina infraestructura, comercio y cooperación institucional. Las oportunidades son claras y los desafíos pasan por financiamiento y coordinación.' },
      { title: 'Normativa relevante', body: 'Existen marcos normativos en Argentina, Brasil y Uruguay con criterios distintos. La integración requiere alinear definiciones técnicas y plazos.' },
      { title: 'Novedades recientes', body: 'Hay un proyecto reciente en Argentina sobre financiamiento, una agenda preliminar UPM y comunicaciones técnicas regionales.' },
      { title: 'Documentos UPM vinculados', body: '4 documentos institucionales activos.' },
      { title: 'Preguntas para reunión', body: '¿Cuáles son los plazos? ¿Qué organismos quedan a cargo? ¿Cómo se coordinan los criterios técnicos?' },
      { title: 'Actores clave', body: 'Comisiones de transporte y obras públicas, secretarías técnicas, organismos de aduanas y ministerios de infraestructura.' },
      { title: 'Próximos pasos', body: 'Convocar reunión técnica regional y presentar dictamen comparado al Foro UPM.' },
    ],
    documents: ['d2', 'd12', 'd3', 'd4'],
  },
  {
    id: 'ds2',
    title: 'Dossier — Ambiente y reporte regional',
    topic: 'ambiente',
    updatedAt: '2026-05-02',
    summary:
      'Nuevo marco regulatorio en Brasil y comparativa con países vecinos. Foco: trazabilidad, sanciones y coordinación binacional.',
    sections: [
      { title: 'Resumen ejecutivo', body: 'Brasil avanza con un decreto que actualiza criterios. Hay impacto regional y oportunidad de cooperación.' },
      { title: 'Normativa relevante', body: 'Ley UY de Protección Ambiental, decretos provinciales y reglamentaciones brasileñas recientes.' },
      { title: 'Documentos UPM vinculados', body: '3 documentos del Foro de Medio Ambiente.' },
      { title: 'Preguntas para reunión', body: '¿Qué se reporta? ¿Quién audita? ¿Cómo se coordinan zonas fronterizas?' },
      { title: 'Próximos pasos', body: 'Pedir minuta técnica al Foro Ambiental UPM.' },
    ],
    documents: ['d1', 'd5', 'd8'],
  },
]

export const FOLDERS: Folder[] = [
  { id: 'f1', title: 'Comisión Ambiente', itemCount: 7, description: 'Material para próxima comisión' },
  { id: 'f2', title: 'Reunión Brasil — Uruguay', itemCount: 4, description: 'Documentos de preparación' },
  { id: 'f3', title: 'Foro Corredores', itemCount: 9, description: 'Trabajo en curso' },
  { id: 'f4', title: 'Documentos para entrevista', itemCount: 3 },
  { id: 'f5', title: 'Pendientes legislativos', itemCount: 12, description: 'Seguimiento personal' },
]

export const AGENDA: AgendaEvent[] = [
  {
    id: 'a1',
    title: 'Foro UPM de Ambiente',
    date: '2026-05-12',
    participants: 'Legisladores y referentes técnicos',
    status: 'pendiente',
    documents: 4,
    topic: 'ambiente',
  },
  {
    id: 'a2',
    title: 'Reunión bilateral Argentina — Brasil',
    date: '2026-05-15',
    participants: 'Comisiones bilaterales',
    status: 'pendiente',
    documents: 3,
    topic: 'integracion-regional',
  },
  {
    id: 'a3',
    title: 'Comisión sobre integración logística',
    date: '2026-05-19',
    participants: 'Comisión técnica regional',
    status: 'preparado',
    documents: 5,
    topic: 'corredores-bioceanicos',
  },
  {
    id: 'a4',
    title: 'Seminario académico regional',
    date: '2026-05-22',
    participants: 'Centros académicos asociados',
    status: 'pendiente',
    documents: 2,
    topic: 'integracion-regional',
  },
]

export const FORUMS: Forum[] = [
  { id: 'fo1', title: 'Foro de Medio Ambiente', topic: 'ambiente', members: 18, documents: 24, upcoming: '2026-05-12', description: 'Coordinación regional sobre marcos normativos ambientales.' },
  { id: 'fo2', title: 'Foro de Corredores Bioceánicos', topic: 'corredores-bioceanicos', members: 14, documents: 19, upcoming: '2026-05-19', description: 'Integración física, financiamiento e infraestructura regional.' },
  { id: 'fo3', title: 'Foro de Río Uruguay', topic: 'rio-uruguay', members: 9, documents: 11, upcoming: '2026-06-02', description: 'Coordinación binacional sobre cuenca del Río Uruguay.' },
  { id: 'fo4', title: 'Foro de Género', topic: 'genero', members: 22, documents: 16, upcoming: '2026-05-28', description: 'Iniciativas conjuntas sobre paridad y representación.' },
  { id: 'fo5', title: 'Foro Académico', topic: 'integracion-regional', members: 31, documents: 42, upcoming: '2026-05-22', description: 'Centros de estudios y aportes técnicos regionales.' },
  { id: 'fo6', title: 'Foro de Relaciones Internacionales', topic: 'rrii', members: 12, documents: 9, upcoming: '2026-06-10', description: 'Coordinación de tratados y agenda exterior parlamentaria.' },
]

export const DEMO_OPERATOR = {
  email: 'martin.pereira@upm.org',
  name: 'Dr. Martín Pereira',
  cargo: 'Legislador',
  pais: 'UY' as CountryCode,
}

export const DEFAULT_PREFS = {
  countries: ['AR', 'BR', 'UY', 'PY'] as CountryCode[],
  topics: ['ambiente', 'integracion-regional', 'corredores-bioceanicos', 'mercosur'] as Topic[],
  frequency: 'diario' as const,
  language: 'es' as const,
  notifications: true,
}
